### ISSUE TITLE
[Bug] Deprecated fields

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [fivetran/dbt_asana_source#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

This package looks like it's still including [fields that are deprecated ](https://fivetran.com/docs/applications/asana/changelog#june2021) within the package. For example, the following fields have been deprecated from the `TASK` table:
- `assignee_status`
- `hearted`
- `num_hearts`

There may be others as well.

Some of these fields are included in the models, some are just in the macros. Either way, may be good to clean up this package to only include fields that are supported.

### Expected behavior

Only creating models and relevant macros for fields that are supported.

### dbt Project configurations

Refer to internal documentation for location for Asana data

### Package versions

packages:
- package: fivetran/fivetran_utils
  version: [">=0.3.0", "<0.4.0"]

### What database are you using dbt with?

redshift, snowflake, bigquery

### dbt Version

1.0.0

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
This bug has been addressed in the latest release v0.6.0. Please check the release notes for more info. Closing this issue.
