### ISSUE TITLE
[Feature] Postgres Compatibility

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_asana_source#22]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This package currently does not support Postgres as a destination. This feature would be to incorporate the proper code changes to support Postgres compatibility.

### Describe alternatives you've considered

Not using Postgres which is not ideal.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Similar work was done within PRs for [dbt_intercom_source](https://github.com/fivetran/dbt_intercom_source/pull/18) and [dbt_intercom](https://github.com/fivetran/dbt_intercom/pull/25) show the efforts needed to ensure Postgres compatiblity.

**Comment by fivetran-joemarkiewicz** [comment]
FYI these changes will need to have updates within the transform package ([dbt_asana](https://github.com/fivetran/dbt_asana)) as well.

**Comment by fivetran-catfritz** [comment]
This bug has been addressed in the latest release v0.6.0. Please check the release notes for more info. Closing this issue.
