### ISSUE TITLE
[Feature] README and Source Identifier Updates

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_asana_source#23]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

A number of our newer packages have an updated README (see [dbt_microsoft_ads_source](https://github.com/fivetran/dbt_microsoft_ads_source) and [dbt_microsoft_ads](https://github.com/fivetran/dbt_microsoft_ads) as examples) to enhance the user experience when using our packages. It would be ideal if we can ensure the Asana package receives the same updates.

Additionally, with this update we will also want to add the source identifier variables to the Asana source file. This allows for a better docs experiences and for users to more user dynamic flexibility. See the open PR for [dbt_quickbooks_source](https://github.com/fivetran/dbt_quickbooks_source/pull/27) to understand what the source identifier updates are and how to apply them. The key files that are changed include the `src_quickbooks.yml` (with the [identifier variable](https://github.com/fivetran/dbt_quickbooks_source/blob/feature/package-updates/models/src_quickbooks.yml#L15) additions) and the [integration_tests/dbt_project.yml](https://github.com/fivetran/dbt_quickbooks_source/blob/5793f7de10de3a94aedf0bdcbfb2b4ce82daf6f0/integration_tests/dbt_project.yml#L10-L48) file with the use of the identifier variables instead of see references.

### Describe alternatives you've considered

Using the old version of the README and not having identifier variables. This is not ideal.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Refer to the PRs and READMEs linked in the feature description for guidance on what updates need to be applied.

**Comment by fivetran-joemarkiewicz** [comment]
FYI these changes will need to have updates within the transform package ([dbt_asana](https://github.com/fivetran/dbt_asana)) as well.

**Comment by fivetran-catfritz** [comment]
This bug has been addressed in the latest release v0.6.0. Please check the release notes for more info. Closing this issue.
